[bell]
animation = "EaseOutExpo"
duration = 0
#color = "#000000"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7f8c8d"
blue = "#3daee9"
cyan = "#16a085"
green = "#1cdc9a"
magenta = "#8e44ad"
red = "#c0392b"
white = "#ffffff"
yellow = "#fdbc4b"

[colors.dim]
black = "#31363b"
blue = "#1b668f"
cyan = "#186c60"
green = "#17a262"
magenta = "#614a73"
red = "#783228"
white = "#63686d"
yellow = "#b65619"

[colors.normal]
black = "#232627"
blue = "#1d99f3"
cyan = "#1abc9c"
green = "#11d116"
magenta = "#9b59b6"
red = "#ed1515"
white = "#fcfcfc"
yellow = "#f67400"

[colors.primary]
background = "#232627"
foreground = "#fcfcfc"

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
multiplier = 1

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_title = true
opacity = 0.85
blur = true

[window.dimensions]
columns = 120
lines = 48

[window.padding]
x = 2
y = 2

[general]
live_config_reload = true
