tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"


################################################################################
# Desktop

### Media

cask "spotify"
cask "steam"
cask "beardedspice"

### Web

cask "firefox"
cask "google-chrome"
cask "stats"

### Services

cask "enpass"
cask "keepingyouawake"

# Productivity

cask "obsidian"
cask "anki"

## Communications

cask "slack"
cask "discord"
cask "signal"

################################################################################
# Development

### CLI

brew "chezmoi"
brew "tmux"
brew "coreutils"
brew "git"
brew "pv"
brew "rdfind"
brew "rsync"
brew "htop"
brew "jq"
brew "yq"
brew "d2"
brew "tealdeer"

### Editors

brew "neovim"
cask "alacritty"
cask "visual-studio-code"

cask "font-roboto-mono-for-powerline"
cask "font-roboto-mono-nerd-font"

### Containers

brew "colima"
brew "docker"

### Security

brew "ykman"
brew "yubico-piv-tool"

### System

# Required for versions of SSH that support SSH resident keys
brew "openssh"

brew "kopia"
cask "kopiaui"

### Network

cask "zerotier-one"
